[package]
name = "examples"
version = "0.1.0"
publish = false
edition.workspace = true

[dependencies]
eired-display = { path = "../eired-display" }
eired-runtime = { path = "../eired-runtime" }
eired= { path = "../eired" }

crossbeam.workspace = true

[[example]]
name = "engine"
path = "engine.rs"
